CREATE TABLE ADMINISTRADOR
(
	ID		INTEGER NOT NULL,
	LOGIN		VARCHAR(8) NOT NULL,
	SENHA		VARCHAR(16) NOT NULL,
	NOME 		VARCHAR(60) NOT NULL,
	PRIMARY KEY (LOGIN)
);

INSERT INTO ADMINISTRADOR (ID, LOGIN, SENHA, NOME) VALUES (1, 'RFSILVA', 'RFSILVA', 'RODRIGO FELICIANO DA SILVA');

CREATE TABLE CARGO
(
	CODIGO		INTEGER NOT NULL,
	DESCRICAO	VARCHAR(50) NOT NULL,
	PRIMARY KEY (CODIGO)
);

INSERT INTO CARGO (CODIGO, DESCRICAO) VALUES (1, 'ANALISTA DE SISTEMAS');
INSERT INTO CARGO (CODIGO, DESCRICAO) VALUES (2, 'PROGRAMADOR');
INSERT INTO CARGO (CODIGO, DESCRICAO) VALUES (3, 'TERAPEUTA OCUPACIONAL');
INSERT INTO CARGO (CODIGO, DESCRICAO) VALUES (4, 'ESTAGIÁRIO');

CREATE TABLE MOEDA
(
	CODIGO		INTEGER NOT NULL,
	SIGLA		VARCHAR(5) NOT NULL,
	NOME		VARCHAR(20) NOT NULL,
	CONVERSAO	FLOAT,
	PRIMARY KEY (CODIGO)
);

INSERT INTO MOEDA (CODIGO, SIGLA, NOME, CONVERSAO) VALUES (1, 'R$', 'REAL', 0.3);
INSERT INTO MOEDA (CODIGO, SIGLA, NOME, CONVERSAO) VALUES (2, 'US$', 'DÓLAR', 2.89);

CREATE TABLE PESSOA
(
	ID		INTEGER NOT NULL,
	PRIMEIRO_NOME	VARCHAR(20) NOT NULL,
	SOBRENOME	VARCHAR(40) NOT NULL,
	APELIDO		VARCHAR(30),
	NASCIMENTO	TIMESTAMP,
	SEXO		VARCHAR(1) NOT NULL,
	CARGO		INTEGER NOT NULL,
	SALARIO		FLOAT NOT NULL,
	MOEDA		INTEGER NOT NULL,
	DIA_PAGTO	INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (MOEDA) REFERENCES MOEDA (CODIGO),
	FOREIGN KEY (CARGO) REFERENCES CARGO (CODIGO)
);

CREATE TABLE LOGIN
(
	LOGIN 		VARCHAR(8) NOT NULL,
	SENHA	 	VARCHAR(16) NOT NULL,
	ID 		INTEGER NOT NULL,
	PRIMARY KEY (LOGIN),
	FOREIGN KEY (ID) REFERENCES PESSOA (ID)
);

CREATE TABLE TIPOLOCALIZACAO
(
	CODIGO 		INTEGER NOT NULL,
	NOME		VARCHAR(20) NOT NULL,
	SIGLA		VARCHAR(5) NOT NULL,
	PRIMARY KEY (CODIGO)
);

INSERT INTO TIPOLOCALIZACAO (CODIGO, NOME, SIGLA) VALUES (1, 'RUA', 'R.');
INSERT INTO TIPOLOCALIZACAO (CODIGO, NOME, SIGLA) VALUES (2, 'LOGRADOURO', 'LOG.');
INSERT INTO TIPOLOCALIZACAO (CODIGO, NOME, SIGLA) VALUES (3, 'TRAVESSA', 'TRAV.');
INSERT INTO TIPOLOCALIZACAO (CODIGO, NOME, SIGLA) VALUES (4, 'AVENIDA', 'AV.');
INSERT INTO TIPOLOCALIZACAO (CODIGO, NOME, SIGLA) VALUES (5, 'RODOVIA', 'ROD.');
INSERT INTO TIPOLOCALIZACAO (CODIGO, NOME, SIGLA) VALUES (6, 'PRAÇA', 'PÇA');

CREATE TABLE ESTADO
(
	CODIGO 		INTEGER NOT NULL,
	SIGLA		VARCHAR(2) NOT NULL,
	NOME		VARCHAR(30) NOT NULL,
	PRIMARY KEY (CODIGO)
);

INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (1, 'AC', 'ACRE');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (2, 'AL', 'ALAGOAS');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (3, 'AM', 'AMAZONAS');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (4, 'AP', 'AMAPÁ');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (5, 'BA', 'BAHIA');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (6, 'CE', 'CEARÁ');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (7, 'DF', 'DISTRITO FEDERAL');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (8, 'ES', 'ESPÍRITO SANTO');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (9, 'GO', 'GOIÁS');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (10, 'MA', 'MARANHÃO');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (11, 'MG', 'MINAS GERAIS');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (12, 'MS', 'MATO GROSSO DO SUL');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (13, 'MT', 'MATO GROSSO');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (14, 'PA', 'PARÁ');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (15, 'PB', 'PARAÍBA');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (16, 'PE', 'PERNAMBUCO');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (17, 'PI', 'PIAUÍ');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (18, 'PR', 'PARANÁ');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (19, 'RJ', 'RIO DE JANEIRO');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (20, 'RN', 'RIO GRANDE DO NORTE');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (21, 'RO', 'RONDÔNIA');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (22, 'RS', 'RIO GRANDE DO SUL');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (23, 'RR', 'RORAIMA');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (24, 'SC', 'SANTA CATARINA');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (25, 'SE', 'SERGIPE');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (26, 'SP', 'SÃO PAULO');
INSERT INTO ESTADO (CODIGO, SIGLA, NOME) VALUES (27, 'TO', 'TOCANTINS');

CREATE TABLE CONTINENTE
(
	CODIGO 		INTEGER NOT NULL,
	NOME		VARCHAR(20) NOT NULL,
	PRIMARY KEY (CODIGO)
);

INSERT INTO CONTINENTE (CODIGO, NOME) VALUES (1, 'ÁFRICA');
INSERT INTO CONTINENTE (CODIGO, NOME) VALUES (2, 'AMÉRICA CENTRAL');
INSERT INTO CONTINENTE (CODIGO, NOME) VALUES (3, 'AMÉRICA DO NORTE');
INSERT INTO CONTINENTE (CODIGO, NOME) VALUES (4, 'AMÉRICA DO SUL');
INSERT INTO CONTINENTE (CODIGO, NOME) VALUES (5, 'ÁSIA');
INSERT INTO CONTINENTE (CODIGO, NOME) VALUES (6, 'EUROPA');
INSERT INTO CONTINENTE (CODIGO, NOME) VALUES (7, 'OCEANIA');

CREATE TABLE PAIS
(
	CODIGO		INTEGER NOT NULL,
	NOME		VARCHAR(50) NOT NULL,
	CONTINENTE	INTEGER NOT NULL,
	PRIMARY KEY (CODIGO),
	FOREIGN KEY (CONTINENTE) REFERENCES CONTINENTE (CODIGO)	
);

/* AMÉRICA DO SUL */
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (1, 'ARGENTINA', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (2, 'BRASIL', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (3, 'CHILE', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (4, 'COLÔMBIA', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (5, 'URUGUAI', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (6, 'PARAGUAI', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (7, 'BOLÍVIA', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (8, 'PERU', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (9, 'EQUADOR', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (10, 'VENEZUELA', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (11, 'GUIANA', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (12, 'SURINAME', 4);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (13, 'GUIANA FRANCESA', 4);

/* AMÉRICA DO NORTE */
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (14, 'CANADÁ', 3);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (15, 'ESTADOS UNIDOS', 3);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (16, 'MÉXICO', 3);

/* AMÉRICA CENTRAL */
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (17, 'ANGUILLA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (18, 'ANTÍGUA & BARBUDA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (19, 'ANTILHAS HOLANDESAS', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (20, 'ARUBA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (21, 'BAHAMAS', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (22, 'BARBADOS', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (23, 'BELIZE', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (24, 'BERMUDAS', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (25, 'COSTA RICA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (26, 'CUBA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (27, 'DOMINICA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (28, 'EL SALVADOR', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (29, 'GRANADA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (30, 'GUADALUPE', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (31, 'GUATEMALA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (32, 'HAITI', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (33, 'HONDURAS', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (34, 'ILHAS CAYMAN', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (35, 'JAMAICA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (36, 'MARTINICA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (37, 'NICARÁGUA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (38, 'PANAMÁ', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (39, 'PORTO RICO', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (40, 'REPÚBLICA DOMINICANA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (41, 'SANTA HELENA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (42, 'SANTA LÚCIA', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (43, 'SÃO CRISTÓVÃO & NEVES', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (44, 'SÃO PEDRO & MIQUELON', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (45, 'SÃO VICENTE & GRANADINAS', 2);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (46, 'TRINIDAD & TOBAGO', 2);


/* ÁSIA */
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (47, 'AFEGANISTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (48, 'ARÁBIA SAUDITA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (49, 'ARMÊNIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (50, 'AZERBAIJÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (51, 'BAHREIN', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (52, 'BANGLADESH', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (53, 'BELARUS', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (54, 'BRUNEI', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (55, 'BUTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (56, 'CAZAQUISTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (57, 'CHINA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (58, 'CINGAPURA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (59, 'CORÉIA DO NORTE', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (60, 'CORÉIA DO SUL', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (61, 'EMIRADOS ÁRABES UNIDOS', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (62, 'FILIPINAS', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (63, 'GEÓRGIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (64, 'HONG KONG', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (65, 'IÊMEN', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (66, 'ÍNDIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (67, 'INDONÉSIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (68, 'IRÃ', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (69, 'IRAQUE', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (70, 'ISRAEL', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (71, 'JAPÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (72, 'JORDÂNIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (73, 'KUWAIT', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (74, 'OMÃ', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (75, 'LÍBANO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (76, 'MALÁSIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (77, 'MONGÓLIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (78, 'MYANMAR', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (79, 'NEPAL', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (80, 'PALESTINA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (81, 'PAQUISTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (82, 'QATAR', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (83, 'QUIRGUISTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (84, 'SÍRIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (85, 'SRI LANKA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (86, 'TADJIQUISTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (87, 'TAILÂNDIA', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (88, 'TAIWAN', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (89, 'TIMOR LESTE', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (90, 'TURCOMENISTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (91, 'UZBEQUISTÃO', 5);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (92, 'VIETNÃ', 5);

/* ÁFRICA */
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (93, 'ÁFRICA DO SUL', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (94, 'ANGOLA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (95, 'ARGÉLIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (96, 'BENIN', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (97, 'BOTSUANA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (98, 'BURKINA-FASSO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (99, 'BURUNDI', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (100, 'CABO VERDE', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (101, 'CAMARÕES', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (102, 'CHADE', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (103, 'CONGO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (104, 'COSTA DO MARFIM', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (105, 'DJIBUTI', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (106, 'EGITO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (107, 'ERITRÉIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (108, 'ETIÓPIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (109, 'GABÃO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (110, 'GÂMBIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (111, 'GANA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (112, 'GUINÉ', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (113, 'GUINÉ-BISSAU', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (114, 'GUINÉ EQUATORIAL', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (115, 'LAOS', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (116, 'LESOTO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (117, 'LIBÉRIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (118, 'LÍBIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (119, 'MADAGASCAR', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (120, 'MALAWI', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (121, 'MALDIVAS', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (122, 'MALI', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (123, 'MARROCOS', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (124, 'MAURÍCIO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (125, 'MAURITÂNIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (126, 'MOÇAMBIQUE', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (127, 'NAMÍBIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (128, 'NÍGER', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (129, 'NIGÉRIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (130, 'QUÊNIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (131, 'REPÚBLICA CENTRO-AFRICANA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (132, 'REPÚBLICA DEMOCRÁTICA DO CONGO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (133, 'RUANDA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (134, 'SÃO TOMÉ & PRÍNCIPE', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (135, 'SENEGAL', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (136, 'SERRA LEOA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (137, 'SEYCHELLES', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (138, 'SOMÁLIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (139, 'SUAZILÂNDIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (140, 'SUDÃO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (141, 'TANZÂNIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (142, 'TOGO', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (143, 'TUNÍSIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (144, 'UGANDA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (145, 'ZAIRE', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (146, 'ZÂMBIA', 1);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (147, 'ZIMBÁBUE', 1);

/* EUROPA */
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (148, 'PORTUGAL', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (149, 'ALBÂNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (150, 'ALEMANHA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (151, 'ANDORRA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (152, 'ÁUSTRIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (153, 'BELGICA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (154, 'BÓSNIA-HERZEGOVINA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (155, 'BULGÁRIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (156, 'CHIPRE', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (157, 'CROÁCIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (158, 'DINAMARCA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (159, 'ESCÓCIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (160, 'ESLOVÁQUIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (161, 'ESLOVÊNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (162, 'ESPANHA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (163, 'ESTÔNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (164, 'FAEROE', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (165, 'FINLÂNDIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (166, 'FRANÇA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (167, 'GIBRALTAR', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (168, 'GRÉCIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (169, 'HOLANDA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (170, 'HUNGRIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (171, 'INGLATERRA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (172, 'IRLANDA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (173, 'IRLANDA DO NORTE', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (174, 'ISLÂNDIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (175, 'ITÁLIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (176, 'IUGOSLÁVIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (177, 'JERSEY', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (178, 'KOSOVO', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (179, 'LETÔNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (180, 'LIECHTENSTEIN', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (181, 'LITUÂNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (182, 'LUXEMBURGO', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (183, 'MACEDÔNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (184, 'MALTA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (185, 'MOLDOVA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (186, 'MÔNACO', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (187, 'MONTSERRAT', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (188, 'NORUEGA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (189, 'PAÍS DE GALES', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (190, 'POLÔNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (191, 'PORTUGAL', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (192, 'REINO UNIDO', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (193, 'REPÚBLICA TCHECA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (194, 'ROMÊNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (195, 'RÚSSIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (196, 'SAN MARINO', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (197, 'SÉRVIA E MONTENEGRO', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (198, 'SUÉCIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (199, 'SUÍÇA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (200, 'TURQUIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (201, 'UCRÂNIA', 6);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (202, 'VATICANO', 6);

/* OCEANIA */
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (203, 'AUSTRÁLIA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (204, 'COMORES', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (205, 'FIJI', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (206, 'GUAM', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (207, 'GUERNSEY', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (208, 'ILHA DE MAN', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (209, 'ILHAS CAROLINAS', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (210, 'ILHAS CHRISTMAS', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (211, 'ILHAS COCOS', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (212, 'ILHAS COOK', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (213, 'ILHAS MARSHALL', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (214, 'ILHAS PITCAIRN', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (215, 'ILHAS SALOMÃO', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (216, 'ILHAS TOKELAU', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (217, 'ILHAS TURKS & CAICOS', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (218, 'ILHAS VIRGENS AMERICANAS', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (219, 'ILHAS VIRGENS BRITÂNICAS', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (220, 'ILHAS WALLIS & FUTUNA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (221, 'KIRIBATI', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (222, 'MACAU', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (223, 'MARIANAS DO NORTE', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (224, 'MICRONÉSIA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (225, 'NAURU', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (226, 'NIUE', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (227, 'NORFOLK', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (228, 'NOVA CALEDÔNIA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (229, 'NOVA ZELÂNDIA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (230, 'PALAU', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (231, 'PAPUA-NOVA GUINÉ', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (232, 'POLINÉSIA FRANCESA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (233, 'SAMOA AMERICANA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (234, 'SAMOA OCIDENTAL', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (235, 'TONGA', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (236, 'TRANSKEY', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (237, 'TUVALU', 7);
INSERT INTO PAIS (CODIGO, NOME, CONTINENTE) VALUES (238, 'VANUATU', 7);

CREATE TABLE ENDERECO
(
	ID		INTEGER NOT NULL,
	TIPO		INTEGER NOT NULL,
	ENDERECO	VARCHAR(50) NOT NULL,
	NUMERO		INTEGER,
	BAIRRO		VARCHAR(20),
	CIDADE		VARCHAR(50) NOT NULL,
	ESTADO		INTEGER NOT NULL,
	CEP		VARCHAR(10),
	PAIS		INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (TIPO) REFERENCES TIPOLOCALIZACAO (CODIGO),
	FOREIGN KEY (ESTADO) REFERENCES ESTADO (CODIGO),
	FOREIGN KEY (PAIS) REFERENCES PAIS (CODIGO),
	FOREIGN KEY (ID) REFERENCES PESSOA (ID)
);

CREATE TABLE EMAIL
(
	ID		INTEGER NOT NULL,
	EMAIL		VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID, EMAIL),
	FOREIGN KEY (ID) REFERENCES PESSOA (ID)
);

CREATE TABLE TELEFONE
(
	ID 		INTEGER NOT NULL,
	DDD		INTEGER NOT NULL,
	TELEFONE	VARCHAR(9) NOT NULL,
	PRIMARY KEY (ID, DDD, TELEFONE),
	FOREIGN KEY (ID) REFERENCES PESSOA (ID)
);

CREATE TABLE CATEGORIA
(
	CODIGO 		INTEGER NOT NULL,
	NOME		VARCHAR(60) NOT NULL,
	PRIMARY KEY (CODIGO)
);

INSERT INTO CATEGORIA (CODIGO, NOME) VALUES (1, 'DIVERSÃO');

CREATE TABLE TIPOCONTA
(
	CODIGO 		INTEGER NOT NULL,
	TIPO		VARCHAR(16) NOT NULL,
	DESCRICAO	VARCHAR(60),
	SITUACAO	CHAR(1) NOT NULL,
	CATEGORIA	INTEGER NOT NULL,
	PRIMARY KEY (CODIGO),
	FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (CODIGO)
);

INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (1, 'TELEFONE', 'CONTA DE TELEFONE', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (2, 'ÁGUA', 'CONTA DE ÁGUA', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (3, 'LUZ', 'CONTA DE LUZ', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (4, 'ALUGUEL', 'ALUGUEL DA RESIDÊNCIA', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (5, 'IPTU', 'IMPOSTO PREDIAL SOBRE TERRENOS URBANOS', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (6, 'IPVA', 'IMPOSTO PREDIAL SOBRE VEÍCULOS AUTOMOTORES', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (7, 'SEGURO', 'SEGURO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (8, 'PROVEDOR', 'PROVEDOR DE ACESSO À INTERNET', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (9, 'CONDOMÍNIO', 'VALOR DO CONDOMÍNIO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (10, 'VIAGEM', 'DESPESA DE VIAGEM IDA/VOLTA', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (11, 'DIVERSOS', 'CONTAS DIVERSAS', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (12, 'ALIMENTAÇÃO', 'DESPESA DE ALIMENTAÇÃO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (13, 'REMÉDIO', 'DESPESA COM REMÉDIO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (14, 'ACADEMIA', 'MENSALIDADE DA ACADEMIA', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (15, 'MASCOTE', 'DESPESA COM ANIMAIS DE ESTIMAÇÃO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (16, 'COMBUSTÍVEL', 'GASTOS COM COMBUSTÍVEL', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (17, 'FACULDADE', 'MENSALIDADE DA FACULDADE', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (18, 'CONGRESSO', 'CONGRESSO/SEMINÁRIO/SIMPÓSIO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (19, 'CHEQUE', 'CHEQUE PASSADO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (20, 'SUPERMERCADO', 'GASTOS EM SUPERMERCADO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (21, 'TRANSPORTE', 'GASTOS COM TRANSPORTE', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (22, 'SAQUE', 'SAQUE', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (23, 'SALÁRIO', 'SALÁRIO DO MÊS', 'C', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (24, 'DEPÓSITO', 'DEPÓSITO', 'C', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (25, 'BANCO', 'COBERTURA DO LIMITE', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (26, 'MICROCOMPUTADOR', 'DESPESAS COM COMPUTADOR', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (27, 'GÁS', 'DESPESA COM GÁS', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (28, 'EMPRÉSTIMO', 'DINHEIRO PEGO EMPRESTADO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (29, 'COMPRA PARCELADA', 'GASTO COM COMPRAS PARCELADO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (30, 'COMPRA TOTAL', 'GASTO COM COMPRAS PAGO INTEGRAL', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (31, 'PRESENTE PARC.', 'GASTO COM PRESENTE PARCELADO', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (32, 'PRESENTE TOTAL', 'GASTO COM PRESENTE PAGO INTEGRAL', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (33, 'CERVEJA', 'GASTOS COM CERVEJA', 'D', 1);
INSERT INTO "TIPOCONTA" ("CODIGO", "TIPO", "DESCRICAO", "SITUACAO", "CATEGORIA") VALUES (34, 'CINEMA', 'CINEMA', 'D', 1);

CREATE TABLE CONTA
(
	ID 		INTEGER NOT NULL,
	CODIGO		INTEGER NOT NULL,
	VALOR		FLOAT NOT NULL,
	MOEDA		INTEGER NOT NULL,
	VENCIMENTO	TIMESTAMP,
	TIPOCONTA	INTEGER NOT NULL,
	SITUACAO	INTEGER NOT NULL, /* PAGA OU NÃO PAGA */
	DESCRICAO	VARCHAR(100),
	PRIMARY KEY (ID, CODIGO),
	FOREIGN KEY (ID) REFERENCES PESSOA (ID),
	FOREIGN KEY (MOEDA) REFERENCES MOEDA (CODIGO),
	FOREIGN KEY (TIPOCONTA) REFERENCES TIPOCONTA (CODIGO)
);

CREATE TABLE BANCO
(
	CODIGO		INTEGER NOT NULL,
	NOME		VARCHAR(60) NOT NULL,
	PRIMARY KEY (CODIGO)
);

INSERT INTO BANCO (CODIGO, NOME) VALUES (1, 'BANCO DO BRASIL');
INSERT INTO BANCO (CODIGO, NOME) VALUES (2, 'BANESPA');
INSERT INTO BANCO (CODIGO, NOME) VALUES (3, 'SANTANDER');
INSERT INTO BANCO (CODIGO, NOME) VALUES (4, 'ITAÚ');
INSERT INTO BANCO (CODIGO, NOME) VALUES (5, 'UNIBANCO');
INSERT INTO BANCO (CODIGO, NOME) VALUES (6, 'MERCANTIL SP');
INSERT INTO BANCO (CODIGO, NOME) VALUES (7, 'MERCANTIL DO BRASIL');
INSERT INTO BANCO (CODIGO, NOME) VALUES (8, 'CAIXA ECONOMICA FEDERAL');
INSERT INTO BANCO (CODIGO, NOME) VALUES (9, 'CAIXA ECONOMICA ESTADUAL');
INSERT INTO BANCO (CODIGO, NOME) VALUES (10, 'HSBC');
INSERT INTO BANCO (CODIGO, NOME) VALUES (11, 'BANCO REAL');
INSERT INTO BANCO (CODIGO, NOME) VALUES (12, 'SAFRA');
INSERT INTO BANCO (CODIGO, NOME) VALUES (13, 'BRADESCO');

CREATE TABLE CHEQUE
(
	ID		INTEGER NOT NULL,
	NUMERO		INTEGER NOT NULL,
	BANCO		INTEGER NOT NULL,
	AGENCIA		VARCHAR(10),
	CONTA		VARCHAR(10),
	VALOR		FLOAT,
	MOEDA		INTEGER NOT NULL,
	MOTIVO		VARCHAR(30) NOT NULL,
	DATA		TIMESTAMP,
	PRIMARY KEY (ID, NUMERO),
	FOREIGN KEY (ID) REFERENCES PESSOA (ID),
	FOREIGN KEY (BANCO) REFERENCES BANCO (CODIGO),
	FOREIGN KEY (MOEDA) REFERENCES MOEDA (CODIGO)
);


/* GENERATORS */
CREATE GENERATOR ADMIN_GEN;
CREATE GENERATOR BANCO_GEN;
CREATE GENERATOR CARGO_GEN;
CREATE GENERATOR CONTA_GEN;
CREATE GENERATOR MOEDA_GEN;
CREATE GENERATOR PESSOA_GEN;
CREATE GENERATOR TIPOCONTA_GEN;
CREATE GENERATOR TIPOLOCALIZACAO_GEN;

SET GENERATOR ADMIN_GEN TO 1;
SET GENERATOR BANCO_GEN TO 13;
SET GENERATOR CARGO_GEN TO 4;
SET GENERATOR CONTA_GEN TO 0;
SET GENERATOR MOEDA_GEN TO 2;
SET GENERATOR PESSOA_GEN TO 0;
SET GENERATOR TIPOCONTA_GEN TO 24;
SET GENERATOR TIPOLOCALIZACAO_GEN TO 6;

/* TRIGGERS DE AUTOINC */
SET TERM ;^

CREATE TRIGGER AUTOINC_ADMIN FOR ADMINISTRADOR
ACTIVE BEFORE INSERT
AS
BEGIN
	NEW.ID = GEN_ID(ADMIN_GEN, 1);
END^

CREATE TRIGGER AUTOINC_CARGO FOR CARGO
ACTIVE BEFORE INSERT
AS
BEGIN
	NEW.CODIGO = GEN_ID(CARGO_GEN, 1);
END^

CREATE TRIGGER AUTOINC_CONTA FOR CONTA
ACTIVE BEFORE INSERT
AS
BEGIN
	NEW.CODIGO = GEN_ID(CONTA_GEN, 1);
END^

CREATE TRIGGER AUTOINC_MOEDA FOR MOEDA
ACTIVE BEFORE INSERT
AS
BEGIN
	NEW.CODIGO = GEN_ID(MOEDA_GEN, 1);
END^

CREATE TRIGGER AUTOINC_PESSOA FOR PESSOA
ACTIVE BEFORE INSERT
AS
BEGIN
	NEW.ID = GEN_ID(PESSOA_GEN, 1);
END^

CREATE TRIGGER AUTOINC_TIPOCONTA FOR TIPOCONTA
ACTIVE BEFORE INSERT
AS
BEGIN
	NEW.CODIGO = GEN_ID(TIPOCONTA_GEN, 1);
END^

CREATE TRIGGER AUTOINC_TIPOLOCALIZACAO FOR TIPOLOCALIZACAO
ACTIVE BEFORE INSERT
AS
BEGIN
	NEW.CODIGO = GEN_ID(TIPOLOCALIZACAO_GEN, 1);
END^

SET TERM ^;
